version: '3'

services:
    db:
        image: mysql:5.7
        container_name: mysql_host
        environment:
          MYSQL_ROOT_PASSWORD: cPzlABrjzYTsOMXmdMpO
          MYSQL_DATABASE: mysql_db
          MYSQL_USER: uvJVzkiVcTvvGIiootWr
          MYSQL_PASSWORD: cHfWDpIRraRXwKbsYHAt
          TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
        - mysql_data:/var/lib/mysql
        # - ./docker/db/data:/var/lib/mysql
        - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
        - 3306:3306
    # for develop
    phpmyadmin:
        container_name: test_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
        - PMA_ARBITRARY=1
        - PMA_HOSTS=mysql_host
        - PMA_USER=root
        - PMA_PASSWORD=cPzlABrjzYTsOMXmdMpO
        ports:
        - 8080:80

volumes:
    mysql_data: